const products = [
    {
        id: "phantom-alpha",
        name: "Phantom Alpha",
        name_ar: "فانتوم ألفا",
        price: 159,
        originalPrice: 210,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
        description: "Engineered with high-tensile mesh and explosive foam technology. The ultimate choice for high-speed performance.",
        description_ar: "مُصمم بشبكة عالية الشد وتكنولوجيا الرغوة المتفجرة. الخيار الأمثل للأداء عالي السرعة.",
        details: [
            "Breathable mesh upper for maximum airflow",
            "Explosive foam midsole for energy return",
            "Durable rubber outsole for traction",
            "Lightweight design for speed"
        ],
        details_ar: [
            "جزء علوي شبكي قابل للتنفس لأقصى تدفق للهواء",
            "نعل أوسط رغوي متفجر لعائد الطاقة",
            "نعل خارجي مطاطي متين للجر",
            "تصميم خفيف الوزن للسرعة"
        ]
    },
    {
        id: "volt-stealth",
        name: "Volt Stealth",
        name_ar: "فولت ستيلث",
        price: 145,
        originalPrice: 185,
        image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80",
        description: "A masterpiece of stability and style. Glow-in-the-dark accents meet industrial strength materials.",
        description_ar: "تحفة من الاستقرار والأناقة. تلتقي اللمسات المتوهجة في الظلام بالمواد الصناعية القوية.",
        details: [
            "Glow-in-the-dark accents for visibility",
            "Industrial strength materials for durability",
            "Stable sole for balance",
            "Comfortable fit for all-day wear"
        ],
        details_ar: [
            "لمسات تتوهج في الظلام للرؤية",
            "مواد صناعية قوية للمتانة",
            "نعل مستقر للتوازن",
            "ملاءمة مريحة للارتداء طوال اليوم"
        ]
    },
    {
        id: "white-onyx",
        name: "White Onyx",
        name_ar: "وايت أونيكس",
        price: 199,
        originalPrice: 250,
        image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
        description: "The purest expression of minimal design. Premium leather meets an ultra-light carbon sole.",
        description_ar: "أنقى تعبير عن التصميم البسيط. يلتقي الجلد الفاخر بنعل كربوني خفيف للغاية.",
        details: [
            "Premium leather upper for luxury",
            "Ultra-light carbon sole for performance",
            "Minimalist design for style",
            "Soft insole for comfort"
        ],
        details_ar: [
            "جزء علوي من الجلد الفاخر للرفاهية",
            "نعل كربوني خفيف للغاية للأداء",
            "تصميم بسيط للأناقة",
            "نعل داخلي ناعم للراحة"
        ]
    }
];

const translations = {
    en: {
        cart: "Cart",
        dominate: "Dominate",
        every_step: "Every Step",
        hero_sub: "Elite performance meets street luxury. Our new collection is engineered for those who demand more from their footwear.",
        explore: "Explore Collection",
        limited: "— Limited Edition —",
        cod_avail: "COD Available",
        in_stock: "In Stock",
        order_now: "Order Now",
        view_details: "View Details",
        quick_buy: "Quick Buy",
        priority_ship: "Priority Shipping",
        priority_desc: "Free express delivery on all orders",
        pay_arrival: "Pay on Arrival",
        pay_desc: "Zero risk. Inspect before you pay.",
        premium_warranty: "Premium Warranty",
        warranty_desc: "Every pair comes with a 1-year guarantee",
        rights: "© 2024 PHANTOM FOOTWEAR CO. ALL RIGHTS RESERVED.",
        home: "Home",
        shoes: "Shoes",
        sale: "Sale",
        select_size: "Select Size",
        size_chart: "Size Chart",
        quick_order: "Quick Order",
        full_name: "Full Name",
        phone_number: "Phone Number",
        delivery_address: "Delivery Address",
        enter_name: "Enter your full name",
        enter_phone: "Enter your phone number",
        enter_address: "Enter your full delivery address",
        confirm_purchase: "Confirm Purchase",
        ssl_secure: "SSL Secured Checkout",
        product_details: "Product Details",
        shipping_returns: "Shipping & Returns",
        you_may_like: "You May Also Like",
        added_cart: "Added to Cart!",
        order_success: "Order Placed Successfully!",
        cod_desc_short: "Pay with cash upon delivery.",
        cod_title: "Cash on Delivery",
        cod_desc_long: "Pay securely with cash when your shoes arrive.",
        shipping_content: "Free express shipping on all orders over $100. We ship worldwide with premium courier partners (DHL, FedEx). Returns accepted within 30 days of delivery.",
    },
    ar: {
        cart: "السلة",
        dominate: "سيطر على",
        every_step: "كل خطوة",
        hero_sub: "الأداء المتميز يلتقي بفخامة الشارع. مجموعتنا الجديدة مصممة لأولئك الذين يطلبون المزيد من أحذيتهم.",
        explore: "استكشف المجموعة",
        limited: "— إصدار محدود —",
        cod_avail: "الدفع عند الاستلام",
        in_stock: "متوفر",
        order_now: "اطلب الآن",
        view_details: "عرض التفاصيل",
        quick_buy: "شراء سريع",
        priority_ship: "شحن ذو أولوية",
        priority_desc: "توصيل سريع مجاني لجميع الطلبات",
        pay_arrival: "ادفع عند الوصول",
        pay_desc: "بدون مخاطر. افحص قبل الدفع.",
        premium_warranty: "ضمان مميز",
        warranty_desc: "كل زوج يأتي مع ضمان لمدة عام",
        rights: "© 2024 PHANTOM FOOTWEAR CO. جميع الحقوق محفوظة.",
        home: "الرئيسية",
        shoes: "أحذية",
        sale: "تخفيض",
        select_size: "اختر المقاس",
        size_chart: "دليل المقاسات",
        quick_order: "طلب سريع",
        full_name: "الاسم الكامل",
        phone_number: "رقم الهاتف",
        delivery_address: "عنوان التوصيل",
        enter_name: "أدخل اسمك الكامل",
        enter_phone: "أدخل رقم هاتفك",
        enter_address: "أدخل عنوان التوصيل الكامل",
        confirm_purchase: "تأكيد الشراء",
        ssl_secure: "دفع آمن SSL",
        product_details: "تفاصيل المنتج",
        shipping_returns: "الشحن والإرجاع",
        you_may_like: "قد يعجبك أيضًا",
        added_cart: "تمت الإضافة للسلة!",
        order_success: "تم الطلب بنجاح!",
        cod_desc_short: "ادفع نقدًا عند الاستلام.",
        cod_title: "الدفع عند الاستلام",
        cod_desc_long: "ادفع بأمان نقدًا عند وصول حذائك.",
        shipping_content: "شحن سريع مجاني للطلبات التي تزيد عن 100 دولار. نشحن لجميع أنحاء العالم مع شركاء شحن متميزين. يقبل الإرجاع خلال 30 يومًا.",
    }
};
